Output docs/assets/demo.gif

Set FontSize 14
Set Width 800
Set Height 700
Set WindowBar Colorful
Set Padding 20

Sleep 1s
Type "hestia"
Enter
Sleep 1s
Type "clear"
Enter
Sleep 1s
Type "hestia create demo -d"
Enter
Sleep 15s
Type "hestia ps"
Enter
Sleep 1s
Type "hestia attach demo"
Enter
Sleep 1s
Type "help"
Enter
Sleep 1.5s
Type "/detach"
Enter
Sleep 1s
Type "hestia stop demo"
Enter
Sleep 1s
Type "hestia rm demo"
Enter
Sleep 1s
