//! The shipped corrections: mods that only ever run on a client, whatever a
//! modpack's `env.server` claims. Lifted from `itzg/docker-minecraft-server`'s
//! `files/modrinth-exclude-include.json` — the one list of its kind anyone
//! maintains — and kept in sync by hand when it moves.
//!
//! A table rather than a bundled data file, following [`crate::skins::defaults`]:
//! it changes only when someone edits this repository, so it belongs in source
//! the compiler checks rather than in JSON parsed at runtime.
//!
//! Entries are **lowercase**, matched against any part of a file's path — a bare
//! name therefore catches every version of it, and matching lowercases only the
//! path.

/// Corrections for one pack, keyed by its source project slug. A pack whose slug
/// is absent here takes the global lists alone.
pub(super) struct PackRules {
    pub(super) slug: &'static str,
    pub(super) excludes: &'static [&'static str],
    pub(super) force_includes: &'static [&'static str],
}

pub(super) const GLOBAL_EXCLUDES: &[&str] = &[
    "3dskinlayers",
    "ae2-emi-crafting",
    "ambientsounds",
    "amecs",
    "animation_overhaul",
    "auudio",
    "axolotlbuckets",
    "badoptimizations",
    "betteradvancements",
    "betterbeds",
    "betterf3",
    "bettergrassify",
    "betterthirdperson",
    "bhmenu",
    "blur",
    "boat-item-view",
    "bobby",
    "cat_jam",
    "chat_heads",
    "chatanimation",
    "cherishedworlds",
    "citresewn",
    "clickadv",
    "cobblemon-ui-tweaks",
    "colorwheel",
    "compass-coords",
    "connectedness",
    "continuity",
    "controlling",
    "craftpresence",
    "crashassistant",
    "cull less leaves",
    "cwb",
    "disablecustomworldsadvice",
    "distraction_free_recipes",
    "drippyloadingscreen",
    "eating-animation",
    "emi_trade",
    "emiffect",
    "emitrades",
    "entity_model_features",
    "entity_texture_features",
    "entityculling",
    "euphoriapatcher",
    "fallingleaves",
    "fancymenu",
    "fast-ip-ping",
    "fastquit",
    "fauxcustomentitydata",
    "feytweaks",
    "figura",
    "forgeconfigscreens",
    "geckolibiriscompat",
    "gpumemleakfix",
    "highlighter",
    "immediatelyfast",
    "immersivedamageindicators",
    "indium",
    "inventory-profiles-next",
    "iris",
    "iris-flywheel",
    "itemborders",
    "itemlocks",
    "justzoom",
    "language-reload",
    "lazy-language-loader",
    "legendarytooltips",
    "loadmyresources",
    "lootbeams",
    "mindfuldarkness",
    "miningspeedtooltips",
    "mousetweaks",
    "nicer-skies",
    "notenoughanimations",
    "oculus",
    "ok_zoomer",
    "overflowingbars",
    "particlerain",
    "pickupnotifier",
    "presencefootsteps",
    "prism",
    "reeses_sodium_options",
    "reforgium",
    "resourcepackoverrides",
    "roughly-enough-items",
    "ryoamiclights",
    "screenshot_viewer",
    "searchables",
    "seasonhud",
    "shouldersurfing",
    "skinlayers3d",
    "smoothswapping",
    "sodium",
    "sorted_enchantments",
    "tooltipfix",
    "visuality",
    "vr-combat",
    "wailastages",
    "welcomescreen",
    "xaeros_minimap",
    "xaerosworldmap",
    "yeetusexperimentus",
    "yungsmenutweaks",
    "zoomify",
    "zume",
];

pub(super) const GLOBAL_FORCE_INCLUDES: &[&str] = &[];

pub(super) const PACKS: &[PackRules] = &[PackRules {
    slug: "cobbleverse",
    excludes: &["cloth-config"],
    force_includes: &[],
}];
