/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkinsRouteImport } from './routes/skins'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as ServersRouteRouteImport } from './routes/servers/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServersIndexRouteImport } from './routes/servers/index'
import { Route as ServersServerIdRouteImport } from './routes/servers/$serverId'
import { Route as InstanceInstanceIdRouteImport } from './routes/instance/$instanceId'

const SkinsRoute = SkinsRouteImport.update({
  id: '/skins',
  path: '/skins',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersRouteRoute = ServersRouteRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersIndexRoute = ServersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServersRouteRoute,
} as any)
const ServersServerIdRoute = ServersServerIdRouteImport.update({
  id: '/$serverId',
  path: '/$serverId',
  getParentRoute: () => ServersRouteRoute,
} as any)
const InstanceInstanceIdRoute = InstanceInstanceIdRouteImport.update({
  id: '/instance/$instanceId',
  path: '/instance/$instanceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/servers': typeof ServersRouteRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/settings': typeof SettingsRoute
  '/skins': typeof SkinsRoute
  '/instance/$instanceId': typeof InstanceInstanceIdRoute
  '/servers/$serverId': typeof ServersServerIdRoute
  '/servers/': typeof ServersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/settings': typeof SettingsRoute
  '/skins': typeof SkinsRoute
  '/instance/$instanceId': typeof InstanceInstanceIdRoute
  '/servers/$serverId': typeof ServersServerIdRoute
  '/servers': typeof ServersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/servers': typeof ServersRouteRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/settings': typeof SettingsRoute
  '/skins': typeof SkinsRoute
  '/instance/$instanceId': typeof InstanceInstanceIdRoute
  '/servers/$serverId': typeof ServersServerIdRoute
  '/servers/': typeof ServersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/servers'
    | '/discover'
    | '/settings'
    | '/skins'
    | '/instance/$instanceId'
    | '/servers/$serverId'
    | '/servers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discover'
    | '/settings'
    | '/skins'
    | '/instance/$instanceId'
    | '/servers/$serverId'
    | '/servers'
  id:
    | '__root__'
    | '/'
    | '/servers'
    | '/discover'
    | '/settings'
    | '/skins'
    | '/instance/$instanceId'
    | '/servers/$serverId'
    | '/servers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ServersRouteRoute: typeof ServersRouteRouteWithChildren
  DiscoverRoute: typeof DiscoverRoute
  SettingsRoute: typeof SettingsRoute
  SkinsRoute: typeof SkinsRoute
  InstanceInstanceIdRoute: typeof InstanceInstanceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skins': {
      id: '/skins'
      path: '/skins'
      fullPath: '/skins'
      preLoaderRoute: typeof SkinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers': {
      id: '/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof ServersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers/': {
      id: '/servers/'
      path: '/'
      fullPath: '/servers/'
      preLoaderRoute: typeof ServersIndexRouteImport
      parentRoute: typeof ServersRouteRoute
    }
    '/servers/$serverId': {
      id: '/servers/$serverId'
      path: '/$serverId'
      fullPath: '/servers/$serverId'
      preLoaderRoute: typeof ServersServerIdRouteImport
      parentRoute: typeof ServersRouteRoute
    }
    '/instance/$instanceId': {
      id: '/instance/$instanceId'
      path: '/instance/$instanceId'
      fullPath: '/instance/$instanceId'
      preLoaderRoute: typeof InstanceInstanceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ServersRouteRouteChildren {
  ServersServerIdRoute: typeof ServersServerIdRoute
  ServersIndexRoute: typeof ServersIndexRoute
}

const ServersRouteRouteChildren: ServersRouteRouteChildren = {
  ServersServerIdRoute: ServersServerIdRoute,
  ServersIndexRoute: ServersIndexRoute,
}

const ServersRouteRouteWithChildren = ServersRouteRoute._addFileChildren(
  ServersRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ServersRouteRoute: ServersRouteRouteWithChildren,
  DiscoverRoute: DiscoverRoute,
  SettingsRoute: SettingsRoute,
  SkinsRoute: SkinsRoute,
  InstanceInstanceIdRoute: InstanceInstanceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
