#!/usr/bin/env python3
"""Write one per-proto-module barrel that re-exports its generated TS types,
plus the types/index.ts that fans them all in. Driven by scripts/gen-types.sh
after ts-rs has written the flat generated/ files.

A type belongs to a module's barrel iff (a) the module declares it and (b) ts-rs
actually generated a file for it — so Contract marker structs (which carry no
`#[ts]` derive and produce no file) are excluded without parsing attributes."""

import glob
import os
import re

SRC = "crates/proto/src"
OUT = "frontend/src/api/types"
GEN = f"{OUT}/generated"
SKIP_MODULES = {"lib", "contract", "naming", "config"}
TYPE_RE = re.compile(r"^pub (?:struct|enum) ([A-Za-z0-9_]+)")

modules = []
for path in sorted(glob.glob(f"{SRC}/*.rs")):
    module = os.path.basename(path)[:-3]
    if module in SKIP_MODULES:
        continue
    names = sorted(
        {
            m.group(1)
            for line in open(path)
            if (m := TYPE_RE.match(line)) and os.path.exists(f"{GEN}/{m.group(1)}.ts")
        }
    )
    if not names:
        continue
    modules.append(module)
    body = "\n".join(f'export type {{ {t} }} from "./generated/{t}";' for t in names)
    open(f"{OUT}/{module}.ts", "w").write(
        f"// Generated by scripts/gen-types.sh — proto::{module} wire types. Do not edit.\n{body}\n"
    )

index = "\n".join(f'export type * from "./{m}";' for m in modules)
open(f"{OUT}/index.ts", "w").write(
    f"// Generated by scripts/gen-types.sh — do not edit.\n{index}\n"
)
print(f"wrote {len(modules)} module barrels + index")
