// Generated by scripts/gen-types.sh — proto::announce wire types. Do not edit.
export type { AnnounceChangedEvent } from "./generated/AnnounceChangedEvent";
export type { AnnounceDismissParams } from "./generated/AnnounceDismissParams";
export type { AnnounceListResult } from "./generated/AnnounceListResult";
export type { Announcement } from "./generated/Announcement";
export type { Severity } from "./generated/Severity";
