// Generated by scripts/gen-types.sh — proto::cache wire types. Do not edit.
export type { CacheEntry } from "./generated/CacheEntry";
export type { CacheInfoResult } from "./generated/CacheInfoResult";
export type { CacheListResult } from "./generated/CacheListResult";
export type { CacheUsage } from "./generated/CacheUsage";
