// Generated by scripts/gen-types.sh — proto::daemon wire types. Do not edit.
export type { DaemonStatusResult } from "./generated/DaemonStatusResult";
export type { DaemonStopParams } from "./generated/DaemonStopParams";
export type { DaemonStopResult } from "./generated/DaemonStopResult";
