// Generated by scripts/gen-types.sh — proto::download wire types. Do not edit.
export type { Checksum } from "./generated/Checksum";
export type { DownloadDoneEvent } from "./generated/DownloadDoneEvent";
export type { DownloadErrorEvent } from "./generated/DownloadErrorEvent";
export type { DownloadProgress } from "./generated/DownloadProgress";
export type { DownloadProgressEvent } from "./generated/DownloadProgressEvent";
export type { DownloadSpec } from "./generated/DownloadSpec";
export type { DownloadStartResult } from "./generated/DownloadStartResult";
export type { HashAlgorithm } from "./generated/HashAlgorithm";
