// Generated by scripts/gen-types.sh — proto::error wire types. Do not edit.
export type { EntryKind } from "./generated/EntryKind";
export type { ErrorInfo } from "./generated/ErrorInfo";
export type { Field } from "./generated/Field";
export type { IoOp } from "./generated/IoOp";
export type { Nameable } from "./generated/Nameable";
export type { ProfileScope } from "./generated/ProfileScope";
export type { Reason } from "./generated/Reason";
export type { Service } from "./generated/Service";
export type { SyncReason } from "./generated/SyncReason";
export type { Task } from "./generated/Task";
export type { Unsupported } from "./generated/Unsupported";
