// Generated by scripts/gen-types.sh — proto::events wire types. Do not edit.
export type { EventsSubscribeParams } from "./generated/EventsSubscribeParams";
export type { EventsSubscribeResult } from "./generated/EventsSubscribeResult";
