// Generated by scripts/gen-types.sh — proto::java wire types. Do not edit.
export type { JavaInstallDoneEvent } from "./generated/JavaInstallDoneEvent";
export type { JavaInstallErrorEvent } from "./generated/JavaInstallErrorEvent";
export type { JavaInstallParams } from "./generated/JavaInstallParams";
export type { JavaInstallPhase } from "./generated/JavaInstallPhase";
export type { JavaInstallProgress } from "./generated/JavaInstallProgress";
export type { JavaInstallProgressEvent } from "./generated/JavaInstallProgressEvent";
export type { JavaInstallResult } from "./generated/JavaInstallResult";
export type { JavaListResult } from "./generated/JavaListResult";
export type { JavaRelease } from "./generated/JavaRelease";
export type { JavaReleasesResult } from "./generated/JavaReleasesResult";
export type { JavaRuntime } from "./generated/JavaRuntime";
export type { JavaUninstallParams } from "./generated/JavaUninstallParams";
