// Generated by scripts/gen-types.sh — proto::job wire types. Do not edit.
export type { JobCancelParams } from "./generated/JobCancelParams";
export type { JobCancelResult } from "./generated/JobCancelResult";
