// Generated by scripts/gen-types.sh — proto::net wire types. Do not edit.
export type { NetworkState } from "./generated/NetworkState";
export type { NetworkStatus } from "./generated/NetworkStatus";
