// Generated by scripts/gen-types.sh — proto::process wire types. Do not edit.
export type { LogSource } from "./generated/LogSource";
export type { LogStream } from "./generated/LogStream";
export type { ProcessExitEvent } from "./generated/ProcessExitEvent";
export type { ProcessInfo } from "./generated/ProcessInfo";
export type { ProcessListResult } from "./generated/ProcessListResult";
export type { ProcessLogLine } from "./generated/ProcessLogLine";
export type { ProcessLogsParams } from "./generated/ProcessLogsParams";
export type { ProcessLogsResult } from "./generated/ProcessLogsResult";
export type { ProcessMetrics } from "./generated/ProcessMetrics";
export type { ProcessMetricsEvent } from "./generated/ProcessMetricsEvent";
export type { ProcessOutputEvent } from "./generated/ProcessOutputEvent";
export type { ProcessRef } from "./generated/ProcessRef";
export type { ProcessSpec } from "./generated/ProcessSpec";
export type { ProcessStartResult } from "./generated/ProcessStartResult";
export type { ProcessStartedEvent } from "./generated/ProcessStartedEvent";
export type { ProcessState } from "./generated/ProcessState";
export type { RestartPolicy } from "./generated/RestartPolicy";
