// Generated by scripts/gen-types.sh — proto::profile wire types. Do not edit.
export type { GlobalProfile } from "./generated/GlobalProfile";
export type { InstanceProfileApplyParams } from "./generated/InstanceProfileApplyParams";
export type { ProfileEditParams } from "./generated/ProfileEditParams";
export type { ProfileEntry } from "./generated/ProfileEntry";
export type { ProfileListResult } from "./generated/ProfileListResult";
export type { ProfileRef } from "./generated/ProfileRef";
