// Generated by scripts/gen-types.sh — proto::screenshot wire types. Do not edit.
export type { Screenshot } from "./generated/Screenshot";
export type { ScreenshotDeleteParams } from "./generated/ScreenshotDeleteParams";
export type { ScreenshotListParams } from "./generated/ScreenshotListParams";
export type { ScreenshotListResult } from "./generated/ScreenshotListResult";
