// Generated by scripts/gen-types.sh — proto::skins wire types. Do not edit.
export type { Cape } from "./generated/Cape";
export type { CapeClearParams } from "./generated/CapeClearParams";
export type { CapeEquipParams } from "./generated/CapeEquipParams";
export type { Skin } from "./generated/Skin";
export type { SkinAddParams } from "./generated/SkinAddParams";
export type { SkinAddResult } from "./generated/SkinAddResult";
export type { SkinEquipParams } from "./generated/SkinEquipParams";
export type { SkinListParams } from "./generated/SkinListParams";
export type { SkinListResult } from "./generated/SkinListResult";
export type { SkinRemoveParams } from "./generated/SkinRemoveParams";
export type { SkinResetParams } from "./generated/SkinResetParams";
export type { SkinSource } from "./generated/SkinSource";
export type { SkinUpdateParams } from "./generated/SkinUpdateParams";
export type { SkinUpdateResult } from "./generated/SkinUpdateResult";
export type { SkinVariant } from "./generated/SkinVariant";
