// Generated by scripts/gen-types.sh — proto::sync wire types. Do not edit.
export type { InstanceSyncStatus } from "./generated/InstanceSyncStatus";
export type { LinkState } from "./generated/LinkState";
export type { SyncAdoptParams } from "./generated/SyncAdoptParams";
export type { SyncAdoptResult } from "./generated/SyncAdoptResult";
export type { SyncConfig } from "./generated/SyncConfig";
export type { SyncSetParams } from "./generated/SyncSetParams";
export type { SyncStatusResult } from "./generated/SyncStatusResult";
export type { SyncTargets } from "./generated/SyncTargets";
export type { TargetLinkState } from "./generated/TargetLinkState";
