// Generated by scripts/gen-types.sh — proto::update wire types. Do not edit.
export type { UpdateCancelledEvent } from "./generated/UpdateCancelledEvent";
export type { UpdateCheckResult } from "./generated/UpdateCheckResult";
export type { UpdateDoneEvent } from "./generated/UpdateDoneEvent";
export type { UpdateDownloadParams } from "./generated/UpdateDownloadParams";
export type { UpdateDownloadResult } from "./generated/UpdateDownloadResult";
export type { UpdateErrorEvent } from "./generated/UpdateErrorEvent";
export type { UpdateInfo } from "./generated/UpdateInfo";
export type { UpdateProgressEvent } from "./generated/UpdateProgressEvent";
