// Generated by scripts/gen-types.sh — proto::warning wire types. Do not edit.
export type { NotSharedReason } from "./generated/NotSharedReason";
export type { WarningInfo } from "./generated/WarningInfo";
